apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: example-project
---
apiVersion: v1
kind: Secret
metadata:
  name: github-pat
  namespace: example-project
  labels:
    kargo.akuity.io/cred-type: git
stringData:
  repoURL: https://github.com/pitoniak32/kargo-demo*.git
  repoURLIsRegex: "true"
  username: pitoniak32
  password: "$GITHUB_PAT"
