apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promote
  namespace: example-project
spec:
  vars:
  - name: gitopsRepoOwner
    value: pitoniak32
  - name: gitopsRepoName
    value: kargo-demo-gitops
  - name: repoURL
    value: "https://github.com/${{ vars.gitopsRepoOwner }}/${{ vars.gitopsRepoName }}.git"
  - name: sourceBranch
    value: main
  - name: targetBranch
    value: stage/test
  - name: imageRepo
    value: ghcr.io/pitoniak32/nginx
  steps:
  - uses: git-clone
    config:
      repoURL: "https://github.com/${{ vars.gitopsRepoOwner }}/${{ vars.gitopsRepoName }}.git"
      checkout:
      - commit: ${{ commitFrom(vars.repoURL).ID }}
        path: ./src
      - branch: env/${{ ctx.stage }}
        path: ./out
        create: true
  # - uses: git-clear
  #   config:
  #     path: ./out
  # Update the image in the Kustomize configuration located at ./src/env/<stage>
  # in the repository.
  # - uses: kustomize-set-image
  #   as: update-image
  #   config:
  #     path: ./src/env/${{ ctx.stage }}
  #     images:
  #     - image: ${{ vars.imageRepo }}
  #       tag: ${{ imageFrom(vars.imageRepo).Tag}}
  # Build the Kustomize configuration in the ./src directory using the env/<stage>
  # overlay to the ./out directory.
  # - uses: kustomize-build
  #   config:
  #     path: ./src/env/${{ ctx.stage }}
  #     outPath: ./out
  # Commit the changes to the Git repository.
  # - uses: git-commit
  #   as: commit
  #   config:
  #     path: ./out
  #     message: ${{ task.outputs['update-image'].commitMessage }}
  # Push the changes to the Git repository.
  # - uses: git-push
  #   config:
  #     path: ./out
  - uses: http
    as: gha-trigger
    retry:
      timeout: 1m
    config:
      method: POST
      url: 'https://api.github.com/repos/${{ vars.gitopsRepoOwner }}/${{ vars.gitopsRepoName }}/actions/workflows/promote.yml/dispatches'
      headers:
      - name: "Accept"
        value: "application/vnd.github+json"
      - name: "X-GitHub-Api-Version"
        value: "2026-03-10"
      - name: "Authorization"
        value: "Bearer ${{ secret('github-pat').password }}"
      body: |
        ${{ quote({
          "ref": "main",
          "inputs": {
            "stage": ctx.stage,
            "image": vars.imageRepo,
            "imageTag": imageFrom(vars.imageRepo).Tag
          }
        }) }}
      successExpression: response.status == 200
      failureExpression: response.status != 200
      outputs:
      - name: workflow_run_id
        fromExpression: response.body.workflow_run_id
  - uses: http
    as: gha-poll
    retry:
      timeout: 10m
    config:
      method: GET
      url: "https://api.github.com/repos/${{ vars.gitopsRepoOwner }}/${{ vars.gitopsRepoName }}/actions/runs/${{ task.outputs['gha-trigger'].workflow_run_id }}"
      successExpression: response.body.status == "completed" && response.body.conclusion == "success"
      failureExpression: response.body.status == "completed" && response.body.conclusion != "success"
