apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: example-project
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: example-warehouse
    sources:
      direct: true
  verification:
    args:
    - name: service-name
      value: app-testing
    analysisTemplates:
    - name: integration-test
      kind: ClusterAnalysisTemplate
    - name: bake-time
      kind: ClusterAnalysisTemplate
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: qa
  namespace: example-project
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: example-warehouse
    sources:
      stages:
      - dev
      autoPromotionOptions:
        selectionPolicy: MatchUpstream
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
  verification:
    args:
    - name: service-name
      value: app-testing
    - name: bake-time
      value: "60"
    analysisTemplates:
    - name: bake-time
      kind: ClusterAnalysisTemplate
    - name: load-testing
      kind: ClusterAnalysisTemplate
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: example-project
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: example-warehouse
    sources:
      stages:
      - dev
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
  verification:
    args:
    - name: service-name
      value: app-testing
    - name: bake-time
      value: "60"
    analysisTemplates:
    - name: bake-time
      kind: ClusterAnalysisTemplate
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
   name: prod
   namespace: example-project
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: example-warehouse
    sources:
      availabilityStrategy: All
      stages:
      - qa
      - uat
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
