apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: example-warehouse
  namespace: example-project
spec:
  subscriptions:
  - image:
      repoURL: ghcr.io/pitoniak32/nginx
      imageSelectionStrategy: Digest
      constraint: latest
      platform: linux/amd64
  - git:
      repoURL: https://github.com/pitoniak32/kargo-demo-gitops.git
      branch: main
